import requests
key = "4dddafc191664c47ab1140145191203"
loc = str(30.723)+","+str(76.789)
url = "https://api.worldweatheronline.com/premium/v1/weather.ashx"+"?q="+loc+"&key="+key+"&format=json"

response = requests.get(url)
# response = response.content.decode("utf-8")

request_type = response.json().get("data").get("request")[0].get("type")
request_type = response.json().get("data").get("request")[0].get("query")

request_type = response.json().get("data").get("current_condition")[0].get("observation_time")
request_type = response.json().get("data").get("current_condition")[0].get("temp_C")
request_type = response.json().get("data").get("current_condition")[0].get("temp_F")
request_type = response.json().get("data").get("current_condition")[0].get("weatherCode")
request_type = response.json().get("data").get("current_condition")[0].get("weatherIconUrl")[0].get("value")
request_type = response.json().get("data").get("current_condition")[0].get("weatherDesc")[0].get("value")

request_type = response.json().get("data").get("current_condition")[0].get("windSpeedMiles")
request_type = response.json().get("data").get("current_condition")[0].get("windSpeedKmph")
request_type = response.json().get("data").get("current_condition")[0].get("winddirDegree")
request_type = response.json().get("data").get("current_condition")[0].get("winddir16Point")
request_type = response.json().get("data").get("current_condition")[0].get("precipMM")
request_type = response.json().get("data").get("current_condition")[0].get("humidity")
request_type = response.json().get("data").get("current_condition")[0].get("visibility")
request_type = response.json().get("data").get("current_condition")[0].get("pressure")
request_type = response.json().get("data").get("current_condition")[0].get("cloudcover")
request_type = response.json().get("data").get("current_condition")[0].get("FeelsLikeC")
f = response.json().get("data").get("current_condition")[0].get("FeelsLikeF")
uv = response.json().get("data").get("current_condition")[0].get("uvIndex")

for day in range(0,14):
    date = response.json().get("data").get("weather")[day].get("date")
    request_type = response.json().get("data").get("weather")[day].get("astronomy")[0].get("sunrise")
    request_type = response.json().get("data").get("weather")[day].get("astronomy")[0].get("sunset")
    request_type = response.json().get("data").get("weather")[day].get("astronomy")[0].get("moonrise")
    request_type = response.json().get("data").get("weather")[day].get("astronomy")[0].get("moonset")
    request_type = response.json().get("data").get("weather")[day].get("astronomy")[0].get("moon_phase")
    request_type = response.json().get("data").get("weather")[day].get("astronomy")[0].get("moon_illumination")
    aaaa = response.json().get("data").get("weather")[day].get("maxtempC")
    aaaa = response.json().get("data").get("weather")[day].get("maxtempF")
    aaaa = response.json().get("data").get("weather")[day].get("mintempC")
    aaaa = response.json().get("data").get("weather")[day].get("mintempF")
    aaaa = response.json().get("data").get("weather")[day].get("totalSnow_cm")
    aaaa = response.json().get("data").get("weather")[day].get("sunHour")
    aaaa = response.json().get("data").get("weather")[day].get("uvIndex")

    for hour in range (0,8):
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("time")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("tempC")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("tempF")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("windspeedMiles")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("windspeedkmph")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("winddirDegree")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("weatherCode")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("winddir16Point")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("weatherIconUrl")[0].get("value")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("weatherDesc")[0].get("value")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("precipMM")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("humidity")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("visibility")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("pressure")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("cloudcover")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("HeatIndexC")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("HeatIndexF")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("DewPointC")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("DewPointF")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("WindChillC")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("WindChillF")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("WindGustMiles")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("WindGustKmph")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("FeelsLikeC")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("FeelsLikeF")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofrain")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofremdry")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofwindy")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofovercast")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofsunshine")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceoffrost")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofhightemp")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceoffog")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofsnow")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("chanceofthunder")
        aaaa = response.json().get("data").get("weather")[day].get("hourly")[hour].get("uvIndex")


# climate averages
for month in range(0,12):
    aaaa = response.json().get("data").get("ClimateAverages")[0].get("month")[month].get("index")
    mond = response.json().get("data").get("ClimateAverages")[0].get("month")[month].get("name")
    aaaa = response.json().get("data").get("ClimateAverages")[0].get("month")[month].get("avgMinTemp")
    aaaa = response.json().get("data").get("ClimateAverages")[0].get("month")[month].get("avgMinTemp_F")
    aaaa = response.json().get("data").get("ClimateAverages")[0].get("month")[month].get("absMaxTemp")
    aaaab = response.json().get("data").get("ClimateAverages")[0].get("month")[month].get("absMaxTemp_F")
    aaaa = response.json().get("data").get("ClimateAverages")[0].get("month")[month].get("avgDailyRainfall")
# print(url)
